### ISSUE TITLE
UnicodeEncodeError on "Create database" step

### ISSUE THREAD

**Issue by dominikl** [openmicroscopy/ansible-role-omero-server#14]
My playbook:
```
# Install the latest release, including PostgreSQL on the same server
- hosts: testserver
  roles:
  - role: openmicroscopy.omero-server
    postgresql_users_databases:
    - user: omero
      password: omero
      databases: [omero]
```

testserver is a Centos 7 running on openstack.

Stacktrace:
```
TASK [openmicroscopy.postgresql : postgres | create database] ******************
task path: /private/etc/ansible/roles/openmicroscopy.postgresql/tasks/databases.yml:13
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/core/database/postgresql/postgresql_db.py
<10.0.51.178> ESTABLISH SSH CONNECTION FOR USER: omero
<10.0.51.178> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=omero -o ConnectTimeout=10 -o ControlPath=/Users/dlindner/.ansible/cp/ansible-ssh-%h-%p-%r 10.0.51.178 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1497281176.71-180579157084543 `" && echo ansible-tmp-1497281176.71-180579157084543="` echo /tmp/ansible-tmp-1497281176.71-180579157084543 `" ) && sleep 0'"'"''
<10.0.51.178> PUT /var/folders/x0/m0cg9g5j0txddgq0qbwv_6dr000ck9/T/tmpGQYtqm TO /tmp/ansible-tmp-1497281176.71-180579157084543/postgresql_db.py
<10.0.51.178> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=omero -o ConnectTimeout=10 -o ControlPath=/Users/dlindner/.ansible/cp/ansible-ssh-%h-%p-%r '[10.0.51.178]'
<10.0.51.178> ESTABLISH SSH CONNECTION FOR USER: omero
<10.0.51.178> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=omero -o ConnectTimeout=10 -o ControlPath=/Users/dlindner/.ansible/cp/ansible-ssh-%h-%p-%r 10.0.51.178 '/bin/sh -c '"'"'setfacl -m u:postgres:rx /tmp/ansible-tmp-1497281176.71-180579157084543/ /tmp/ansible-tmp-1497281176.71-180579157084543/postgresql_db.py && sleep 0'"'"''
<10.0.51.178> ESTABLISH SSH CONNECTION FOR USER: omero
<10.0.51.178> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=omero -o ConnectTimeout=10 -o ControlPath=/Users/dlindner/.ansible/cp/ansible-ssh-%h-%p-%r 10.0.51.178 '/bin/sh -c '"'"'chmod u+x /tmp/ansible-tmp-1497281176.71-180579157084543/ /tmp/ansible-tmp-1497281176.71-180579157084543/postgresql_db.py && sleep 0'"'"''
<10.0.51.178> ESTABLISH SSH CONNECTION FOR USER: omero
<10.0.51.178> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=omero -o ConnectTimeout=10 -o ControlPath=/Users/dlindner/.ansible/cp/ansible-ssh-%h-%p-%r 10.0.51.178 '/bin/sh -c '"'"'chown postgres /tmp/ansible-tmp-1497281176.71-180579157084543/ /tmp/ansible-tmp-1497281176.71-180579157084543/postgresql_db.py && sleep 0'"'"''
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 91, in run
    item_results = self._run_loop(items)
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 274, in _run_loop
    res = self._execute(variables=task_vars)
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 490, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 617, in _execute_module
    self._fixup_perms2(remote_files, remote_user)
  File "/usr/local/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 394, in _fixup_perms2
    ' see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user'.format(res['rc'], res['stderr']))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 21: ordinal not in range(128)

fatal: [10.0.51.178]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
	to retry, use: --limit @/Users/dlindner/Repositories/ansible-role-omero-server/testplaybook.retry

PLAY RECAP *********************************************************************
10.0.51.178                : ok=19   changed=0    unreachable=0    failed=1  
```

**Comment by dominikl** [comment]
Just realized I've not update ansible for ages, will try again after an update.

**Comment by dominikl** [comment]
Ok, after update ansible, the error changed, now it's:
```
TASK [openmicroscopy.postgresql : postgres | create database] *****************************************************************************************************************************************************
fatal: [10.0.51.178]: FAILED! => {"failed": true, "msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chown: invalid user: ‘postgres’\n). For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}
```

**Comment by joshmoore** [comment]
@dominikl : can you show the whole `ansible-playbook` command?

**Comment by dominikl** [comment]
`ansible-playbook -u omero -vvv testplaybook.yml`
(testplaybook.yml is the playbook shown above)

**Comment by dominikl** [comment]
Yes, looks like the unicode issue was that bug; this error is gone after ansible update. But now it seems the su to postgres user does fail. I'll try again from scratch, maybe it's just an artifact from the previous failed installation attempt.

**Comment by joshmoore** [comment]
Ok. Keep us posted:

```
chown: invalid user: ‘postgres’\n
```

certainly looks unicode related as well.

**Comment by dominikl** [comment]
Ok, I tried again, on OSX with an homebrew installed ansible (before it was pip installed), same error. Then I tried with ansible 2.3.1.0 on Arch linux, same error.

**Comment by manics** [comment]
```
python: print '\xe2\x80\x98postgres\xe2\x80\x99'
‘postgres’
```
Have you copied/pasted some curly quotes?

**Comment by dominikl** [comment]
Ok, if that's of any help: I cloned and used https://github.com/openmicroscopy/ansible-public-omero-example . That worked.
Maybe `ansible-galaxy install -r requirements.yml -p roles` instead of `ansible-galaxy install openmicroscopy.omero-server` (what I did before) did the trick!?

**Comment by joshmoore** [comment]
Hmmm.... this all sounds quite odd and my guess is outwith ansible or openstack :+1: for it now working for you.

**Comment by dominikl** [comment]
Well, the error is still perfectly reproducible. Just to sum it up:
- Clone https://github.com/openmicroscopy/ansible-role-omero-server 
- Install `ansible-galaxy install openmicroscopy.omero-server`
- Create and run the example notebook "Install the latest release, including PostgreSQL on the same server"  mentioned at the end of the Readme.md

**Comment by joshmoore** [comment]
Hmmm.... different behavior for me, but still problematic.

Steps:

 * run: `mkdir /tmp/dom`
 * run: `export ANSIBLE_ROLES_PATH=$PWD/vendor`
 * run: `ansible-galaxy install openmicroscopy.omero-server`
 * clone as above, creating test.yml from the README (replacing "localhost" with "test")
 * run: `vagrant init` using centos/7
 * run: `vagrant ssh-config` to create the inventory
 * run: ` ansible-playbook -i inventory test.yml`

## inventory ###
test ansible_user=vagrant ansible_ssh_port=222 ansible_ssh_host=localhost ansible_ssh_private_key_file=/private/tmp/ansible-role-omero-server/.vagrant/machines/default/virtualbox/private_key

### result ###
```
TASK [openmicroscopy.postgresql : postgres | start service] ***************************************************************************
Tuesday 13 June 2017  12:44:03 +0200 (0:00:00.022)       0:18:36.582 **********
skipping: [test]

TASK [openmicroscopy.postgresql : postgres | install ansible prerequisites] ***********************************************************
Tuesday 13 June 2017  12:44:03 +0200 (0:00:00.020)       0:18:36.603 **********
changed: [test] => (item=[u'python-psycopg2'])

TASK [openmicroscopy.postgresql : postgres | create database] *************************************************************************
Tuesday 13 June 2017  12:44:08 +0200 (0:00:04.395)       0:18:40.998 **********
failed: [test] (item=({u'password': u'omero', u'user': u'omero'}, u'omero')) => {"failed": true, "item": [{"password": "omero", "user": "omero"}, "omero"], "module_stderr": "sudo: unknown user: postgres\nsudo: unable to initialize policy plugin\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

PLAY RECAP ****************************************************************************************************************************
test                       : ok=19   changed=15   unreachable=0    failed=1
```


### test.yml ###
```
---
# Install the latest release, including PostgreSQL on the same server
- hosts: test
  roles:
  - role: openmicroscopy.omero-server
    postgresql_users_databases:
    - user: omero
      password: omero
      databases: [omero]
```

cc: @manics

**Comment by manics** [comment]
Looks like the README is out of date, only the postgresql client packages are automatically installed by `omero-server`:

```
    - role: openmicroscopy.postgresql
      postgresql_users_databases:
      - user: omero
        password: omero
        databases: [omero]

- role: openmicroscopy.omero-server
```

**Comment by joshmoore** [comment]
I'll leave you to update to not conflict with anything else in https://github.com/openmicroscopy/ansible-role-omero-server/pull/12 (My worries have returned about embedding code in the READMEs but I still haven't found a good solution a la an `#include`)
